# fly.toml app configuration file generated for mtproxy-ps on 2026-02-10T16:46:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mtproxy-ps'
primary_region = 'ams'

[build]
  image = 'telegrammessenger/proxy:latest'

[[services]]
  protocol = 'tcp'
  internal_port = 443
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[services.ports]]
    port = 443

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
