app = 'mtproxy-fly'
primary_region = 'ams'

[[services]]
  protocol = 'tcp'
  internal_port = 443
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[services.ports]]
    port = 443

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
